CREATE TABLE ESTUDIANTES( 	
    ID            				INTEGER NOT NULL,
    NOMBRES          			VARCHAR2(50) NOT NULL, 
    APELLIDOS        			VARCHAR2(50) NOT NULL, 
    DIRECCION			        VARCHAR2(150), 
    EDAD           			    INTEGER NOT NULL,
    CIUDAD           			VARCHAR2(50),
    PAIS           			    VARCHAR2(50),
   CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) 
 );